### ISSUE TITLE
update table creation (back-end)

### ISSUE THREAD

**Issue by kholoud001** [Youcode-Classe-E-2023-2024/Winners_Blog#57]

**Comment by Benfill** [comment]
please recorrect the table creation and db connection 
Error creating table: Invalid default value for 'soft_delete'
Table Category created successfully
Error creating table: Invalid default value for 'soft_delete'
Error creating table: Invalid default value for 'soft_delete'
Error creating table: Can't create table `blog`.`role` (errno: 150 "Foreign key constraint is incorrectly formed")
Error creating table: Can't create table `blog`.`permission` (errno: 150 "Foreign key constraint is incorrectly formed")
Error creating table: Can't create table `blog`.`user_permission` (errno: 150 "Foreign key constraint is incorrectly formed")
Error creating table: Can't create table `blog`.`passwordrecovery` (errno: 150 "Foreign key constraint is incorrectly formed")

**Comment by kholoud001** [comment]
done
